### ISSUE TITLE
Issues with aimbot, please read.

### ISSUE THREAD

**Issue by theHackor** [humphreygaming/surviv-cheat-source#18]
So I realised that not everyone apparently has this issue (which is even more weird) and I apologise for assuming that it's broken for everyone earlier. but does anybody have any idea why this is happening for me? Here's the video: https://streamable.com/mc5pdj

The aimbot works perfectly fine with melee and auto attack as you can even see it on the video, but as soon as the weapon is picked up, it screws up. It has always been working great, up until the cheat structure was rewritten after one of the surviv patches. 

I tried installing the cheat on chrome and opera browsers, and even now I'm on a different system and it still fails for me. Any suggestions? Thoughts? What could possibly be causing this to happen? 

I could be reaching but it seem as if it sees objects (walls, boxes etc) as enemies and goes completely crazy (the option to shoot at objects is turned off btw)

Since it does work perfectly for some people, is there anything I can try to check if I have installed or turned on in order to fix this? I know you guys don't like these type of posts but ever since I switched to this system, I cannot compile & edit the cheat myself to try and look for a fix myself. I'm sure I'm not alone with this aimbot issue, that wouldn't make any type of sense I think.

Something that is also to be noted is that the aimbot never used to shake the gun the way it does now, it used to work the same way as when you got the melee weapon, aiming straight at opponents. The new cheat structure did something to it and I have no idea what. Maybe it's the mentioned earlier new "return" lines in the aimbot code, I don't know.

**Comment by JIAJIAPNXA** [comment]
same problem
