### ISSUE TITLE
compiler.bat doesn't output to out folder

### ISSUE THREAD

**Issue by mathsmathsmaths** [humphreygaming/surviv-cheat-source#5]
There is an error when trying to compile the code

**Comment by humphreygaming** [comment]
do you have node installed?

**Comment by mathsmathsmaths** [comment]
I think so. Let me check

**Comment by mathsmathsmaths** [comment]
@humphreygaming Node was installed.

**Comment by theHackor** [comment]
Run installer.bat too if it's your first time

**Comment by mathsmathsmaths** [comment]
I did run installer.bat before compiler.bat. All I saw after running compiler.bat was a deprecation message followed by an error message, then disappeared quickly.

**Comment by kraxc** [comment]
@Level 1 Members! - You can view audit log!

**Comment by NotLima** [comment]
rrrtards

**Comment by theHackor** [comment]
@mathsmathsmaths you have an error in the code then most likely
